# Generated by Django 5.1.6 on 2025-06-09 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_category', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_category', models.CharField(max_length=100)),
                ('job_name', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('salary', models.CharField(max_length=100)),
                ('date_of_apply', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('current_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('tender_type', models.CharField(choices=[('open', 'Open Tender'), ('close', 'Close Tender')], max_length=10)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('starting_date', models.DateField()),
                ('number_of_days', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cv/')),
                ('current_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('appointment_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0, verbose_name='Appointment Status')),
                ('appointment_letter', models.FileField(blank=True, null=True, upload_to='appointment_letter/')),
                ('job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portapp.job')),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(auto_now_add=True)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('description', models.TextField()),
                ('interview_link', models.URLField(blank=True, null=True)),
                ('company_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.company_register')),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_list', to='portapp.job_apply')),
            ],
        ),
        migrations.CreateModel(
            name='ExportProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=8)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(default='', max_length=100)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('exporting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('product_description', models.TextField(default='')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('recipient_name', models.CharField(default='', max_length=100)),
                ('recipient_address', models.TextField(default='')),
                ('recipient_contact_number', models.CharField(default='', max_length=15)),
                ('source', models.CharField(default='', max_length=100)),
                ('destination', models.CharField(default='', max_length=100)),
                ('cancel_status', models.IntegerField(default=0)),
                ('refund_status', models.IntegerField(default=0)),
                ('payment_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid'), (2, 'Failed')], default=0)),
                ('user_login', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='contract_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('district', models.CharField(max_length=100)),
                ('registration_id', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replay_text', models.TextField(blank=True, null=True)),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.export')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='company_register',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=4)),
                ('expiry_date', models.CharField(max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_date', models.DateTimeField(auto_now_add=True)),
                ('export', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portapp.export')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_name', models.CharField(max_length=100)),
                ('ship_category', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('ship_description', models.TextField()),
                ('ship_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('location_status', models.CharField(default='Docked', max_length=20)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='export',
            name='ship',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portapp.ship'),
        ),
        migrations.CreateModel(
            name='Shiplocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('company_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.ship')),
            ],
        ),
        migrations.CreateModel(
            name='TenderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('contract_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.tender')),
            ],
        ),
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
            ],
        ),
        migrations.AddField(
            model_name='job_apply',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portapp.user_register'),
        ),
    ]
