# Generated by Django 5.1.6 on 2025-06-09 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(auto_now_add=True)),
                ('current_time', models.TimeField(auto_now_add=True)),
                ('booking_confirmed', models.BooleanField(default=False)),
                ('customs_cleared', models.BooleanField(default=False)),
                ('loaded_on_vessel', models.BooleanField(default=False)),
                ('in_transit', models.BooleanField(default=False)),
                ('arrived_at_port', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('company_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
                ('export', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.export')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.ship')),
            ],
        ),
    ]
