# Generated by Django 5.1.6 on 2025-06-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderapplication',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
