# Generated by Django 5.1.6 on 2025-06-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0004_tenderapplication_bid_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenderapplication',
            old_name='bid_amount',
            new_name='applied_amount',
        ),
    ]
