# Generated by Django 5.1.6 on 2025-06-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0005_rename_bid_amount_tenderapplication_applied_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='unique_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
