# Generated by Django 5.1.6 on 2025-06-14 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0006_export_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderapplication',
            name='contract_agreement',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
        migrations.AlterField(
            model_name='export',
            name='unique_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
