# Generated by Django 5.1.6 on 2025-06-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0008_workstatusreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workstatusreport',
            old_name='contractor',
            new_name='contract',
        ),
    ]
