# Generated by Django 5.1.6 on 2025-06-15 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0009_rename_contractor_workstatusreport_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstatusreport',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login'),
        ),
    ]
