# Generated by Django 5.1.6 on 2025-06-15 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0010_alter_workstatusreport_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portapp.login')),
            ],
        ),
    ]
