# Generated by Django 5.1.6 on 2025-06-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0012_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='import_date',
            field=models.DateField(null=True),
        ),
    ]
