# Generated by Django 5.1.6 on 2025-06-18 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0013_import_import_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='portapp.company_register')),
            ],
        ),
    ]
