# Generated by Django 5.1.6 on 2025-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0014_companynotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='release_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('pending', 'Pending'), ('request_documents', 'Request Documents'), ('documents_submitted', 'Documents Submitted'), ('accepted', 'Accepted')], default='', max_length=20),
        ),
    ]
