# Generated by Django 5.1.6 on 2025-06-18 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0015_import_release_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='import_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('import_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portapp.import')),
            ],
        ),
    ]
