# Generated by Django 5.1.6 on 2025-06-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0016_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='customs_duty_file',
            field=models.FileField(blank=True, null=True, upload_to='import_documents/', verbose_name='Customs Duty Payment Proof'),
        ),
        migrations.AddField(
            model_name='documents',
            name='do_file',
            field=models.FileField(blank=True, null=True, upload_to='import_documents/', verbose_name='Delivery Order (DO)'),
        ),
        migrations.AddField(
            model_name='documents',
            name='import_declaration_file',
            field=models.FileField(blank=True, null=True, upload_to='import_documents/', verbose_name='Import Declaration Form'),
        ),
        migrations.AddField(
            model_name='documents',
            name='kyc_file',
            field=models.FileField(blank=True, null=True, upload_to='import_documents/', verbose_name='KYC Documents'),
        ),
        migrations.AddField(
            model_name='documents',
            name='packing_list_file',
            field=models.FileField(blank=True, null=True, upload_to='import_documents/', verbose_name='Packing List'),
        ),
    ]
