# Generated by Django 5.1.6 on 2025-06-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0017_documents_customs_duty_file_documents_do_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='import',
            name='release_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('pending', 'Pending'), ('request_documents', 'Request Documents'), ('documents_submitted', 'Documents Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='', max_length=20),
        ),
    ]
