# Generated by Django 5.1.6 on 2025-06-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0018_alter_import_release_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='gate_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
