# Generated by Django 5.1.6 on 2025-06-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0019_import_gate_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='ship_type',
            field=models.CharField(choices=[('import', 'Import'), ('export', 'Export')], default='', max_length=10),
        ),
    ]
