# Generated by Django 5.2.3 on 2025-06-28 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0020_ship_ship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='current_date',
            field=models.DateField(default=datetime.datetime(2025, 6, 28, 5, 39, 37, 453651, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='export',
            name='month',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='export',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
