# Generated by Django 5.1.6 on 2025-07-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0021_export_current_date_export_month_export_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='current_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
