# Generated by Django 5.1.6 on 2025-07-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0022_alter_export_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='month',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='export',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
