# Generated by Django 5.1.6 on 2025-07-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0023_alter_export_month_alter_export_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_register',
            name='business_category',
        ),
        migrations.AddField(
            model_name='company_register',
            name='import_export_license',
            field=models.FileField(blank=True, null=True, upload_to='company_licenses/', verbose_name='Import/Export License'),
        ),
        migrations.AddField(
            model_name='company_register',
            name='industry_type',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Logistics', 'Logistics'), ('Exporter', 'Exporter'), ('Manufacturer', 'Manufacturer'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AddField(
            model_name='company_register',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='company_certificates/', verbose_name='Company Registration Certificate'),
        ),
        migrations.AddField(
            model_name='company_register',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Registration Number / CIN'),
        ),
    ]
