# Generated by Django 5.1.6 on 2025-07-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0024_remove_company_register_business_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_register',
            name='import_export_license',
        ),
        migrations.RemoveField(
            model_name='company_register',
            name='registration_certificate',
        ),
    ]
