# Generated by Django 5.1.6 on 2025-07-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0025_remove_company_register_import_export_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='ship_type',
            field=models.CharField(choices=[('Cargo', 'Cargo'), ('Container', 'Container'), ('Oil Tanker', 'Oil Tanker'), ('Bulk Carrier', 'Bulk Carrier')], default='Cargo', max_length=20),
        ),
    ]
