# Generated by Django 5.1.6 on 2025-07-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0026_alter_ship_ship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='flag_state',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='ship',
            name='imo_number',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='mmsi_number',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ship',
            name='year_built',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
