# Generated by Django 5.1.6 on 2025-07-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0027_ship_flag_state_ship_imo_number_ship_mmsi_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='ship_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
