# Generated by Django 5.1.6 on 2025-07-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0028_alter_ship_ship_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='ship_category',
            field=models.CharField(choices=[('Container', 'Container'), ('Oil Tanker', 'Oil Tanker'), ('Bulk Carrier', 'Bulk Carrier'), ('Passenger', 'Passenger')], default='Container', max_length=100),
        ),
        migrations.AlterField(
            model_name='ship',
            name='ship_type',
            field=models.CharField(choices=[('Import', 'Import'), ('Export', 'Export'), ('Both', 'Both')], default='Import', max_length=10),
        ),
    ]
