# Generated by Django 5.1.6 on 2025-07-08 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0030_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='company_login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portapp.login'),
        ),
    ]
