# Generated by Django 5.1.6 on 2025-07-08 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0031_alter_interview_company_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='company_login',
        ),
    ]
