# Generated by Django 5.1.6 on 2025-07-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0032_remove_interview_company_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interview_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Joined', 'Joined')], default='Scheduled', max_length=20),
        ),
    ]
