# Generated by Django 5.1.6 on 2025-07-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portapp', '0034_alter_interview_interview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=20),
        ),
    ]
